name: Rush changed packages
description: Find changed packages and sort them according to review category
inputs:
  rushJsonPath:
    description: Path to rush.json file.
    required: false
    default: './rush.json'
  environment:
    description: Deployment environment.
    required: true
outputs:
  # This action sets dynamic outputs according to deployCategory value in package.json
  # For example all packages with category "k8s" will be grouped in array under outputs.k8s
  tag:
    description: Last deployed tag name.
runs:
  using: node12
  main: dist/index.js
