name: Main workflow
on:
  push:
    branches: ['main']
  pull_request:
    types: ['opened', 'synchronize']
  workflow_dispatch:
    inputs:
      environment:
        description: Manually deploy to selected environment. Default environment - production
          Allowed values - 'production' or 'staging'
        required: false
        default: production
env:
  DEPLOY_ENVIRONMENT: ${{ github.event.inputs.environment }}
jobs:
  main:
    runs-on: ubuntu-latest
    name: A job to test workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build package
        run: npm run build
      - name: Check deploy environment
        run: |
          if [ "$DEPLOY_ENVIRONMENT" != "production" ] && [ "$DEPLOY_ENVIRONMENT" != "staging" ]
          then
              echo "DEPLOY_ENVIRONMENT=staging" >> $GITHUB_ENV
          fi
      - name: Testing rush changed packages action
        uses: ./ # Uses an action in the root directory
        id: test
        with:
          rushJsonPath: ./__mocks__/rush.json
          environment: ${{ env.DEPLOY_ENVIRONMENT }}
      - name: Show AWS projects
        run: echo "AWS Projects - ${{ steps.test.outputs.aws }}"
      - name: Show K8S projects
        run: echo "K8S projects - ${{ steps.test.outputs.k8s }}"
